### ISSUE TITLE
Awaiting Reviews

### ISSUE THREAD

**Issue by GasimGasimzada** [reactjs/az.react.dev#159]
In this issue, I would like others to review the following pages as a fresh set of eyes. You might catch things that I may have missed:

### FAQ

- [x] [AJAX and APIs](https://reactjs.org/docs/faq-ajax.html) #172  
- [x] [Babel, JSX, and Build FAQ](https://az.reactjs.org/docs/faq-build.html) #172 
- [x] [Styling](https://az.reactjs.org/docs/faq-styling.html) #172 
- [x] [Virtual DOM and Internals](https://az.reactjs.org/docs/faq-internals.html) #172 
- [x] [File Structure](https://az.reactjs.org/docs/faq-structure.html) #172 
- [x] [Versioning Policy](https://az.reactjs.org/docs/faq-versioning.html) #172
- [x] [Component State](https://az.reactjs.org/docs/faq-state.html) #172 
- [x] [Passing Functions to Components](https://az.reactjs.org/docs/faq-functions.html) #172 

### Advanced Guides

- [ ] [Refs and the DOM](https://az.reactjs.org/docs/refs-and-the-dom.html)
- [ ] [Render Props](https://az.reactjs.org/docs/render-props.html)
- [ ] [Profiler API](https://az.reactjs.org/docs/profiler.html)
- [ ] [Optimizing Performance](https://az.reactjs.org/docs/optimizing-performance.html)
- [ ] [Reconciliation](https://az.reactjs.org/docs/reconciliation.html)
- [ ] [Strict Mode](https://az.reactjs.org/docs/strict-mode.html)
- [ ] [Static Type Checking](https://az.reactjs.org/docs/static-type-checking.html)
- [ ] [Uncontrolled Components](https://az.reactjs.org/docs/uncontrolled-components.html)
- [ ] [Typechecking with PropTypes](https://az.reactjs.org/docs/typechecking-with-proptypes.html)
- [ ] [React without ES6](https://az.reactjs.org/docs/react-without-es6.html)
- [ ] [React without JSX](https://az.reactjs.org/docs/react-without-jsx.html)
- [ ] [JSX in Depth](https://az.reactjs.org/docs/jsx-in-depth.html)
- [ ] [Portals](https://az.reactjs.org/docs/portals.html)
- [ ] [Integrating with Other Libraries](https://az.reactjs.org/docs/integrating-with-other-libraries.html)
- [ ] [High-Order Components](https://az.reactjs.org/docs/higher-order-components.html)

### Testing

- [ ] [Testing Overview](https://az.reactjs.org/docs/testing.html)
- [ ] [Testing Recipes](https://az.reactjs.org/docs/testing-recipes.html)
- [ ] [Testing Environments](https://az.reactjs.org/docs/testing-environments.html)

### Hooks

- [ ] [Hooks Intro](https://az.reactjs.org/docs/hooks-intro.html)
- [ ] [Hooks Overview](https://az.reactjs.org/docs/hooks-overview.html)
- [ ] [State Hook](https://az.reactjs.org/docs/hooks-state.html)
- [ ] [Effect Hook](https://az.reactjs.org/docs/hooks-effect.html)
- [ ] [Rules of Hooks](https://az.reactjs.org/docs/hooks-rules.html)
- [ ] [Custom Hooks](https://az.reactjs.org/docs/hooks-custom.html)
- [ ] [Hooks API Reference](https://az.reactjs.org/docs/hooks-reference.html)
- [ ] [Hooks FAQ](https://az.reactjs.org/docs/hooks-faq.html)

### Contribution

- [ ] [How to Contribute](https://az.reactjs.org/docs/how-to-contribute.html)
- [ ] [Implementation Notes](https://az.reactjs.org/docs/implementation-notes.html)
- [ ] [Codebase Overview](https://az.reactjs.org/docs/codebase-overview.html)

### Concurrent Mode

- [ ] [Suspense for Data Fetching](https://az.reactjs.org/docs/concurrent-mode-suspense.html)
- [ ] [Concurrent UI Patterns](https://az.reactjs.org/docs/concurrent-mode-patterns.html)
- [ ] [Concurrent Mode Adoption](https://az.reactjs.org/docs/concurrent-mode-adoption.html)
- [ ] [Concurrent Mode API Reference](https://az.reactjs.org/docs/concurrent-mode-reference.html)

**Comment by mehdiyev** [comment]
> * [x]  [Babel, JSX, and Build FAQ](https://az.reactjs.org/docs/faq-build.html)

- How about using "**Xeyr!**" instead of _"Yox!"_?
- How about using "**yazılır**"  instead of _"gedir"_? As `{/* Komment bura yazılır*/}`

> * [x]  [Styling](https://az.reactjs.org/docs/faq-styling.html)

- _Komponentlərə CSS **s**iniflərini **n**ecə **ə**lavə **e**də **b**ilərəm?_ There are no upper cases in original. Also, check all other headings. One more thing, here "I" subject was used (bilərəm) but in some documents such as [Passing Functions to Components](https://az.reactjs.org/docs/faq-functions.html) there is no subject _(Funksiyanı komponent instansiyasına necə bind etmək olar?)_ in question (actually, there are both way translations in first two headings in Passing Functions to Components doc.). So, how about translating it as `Komponentlərə CSS siniflərini necə əlavə etmək olar?`? and try to keep one single convention.
- I think here should be comma: _Əgər yuxarıdakı formalı kodu çox yazırsınızsa,_
- In [Conditional Rendering](https://az.reactjs.org/docs/conditional-rendering.html) documentation "inline" was translated as "sətirdaxili" but here as "eyni-sətrli".
- I suggest "stillərdən daha performanslıdır." instead of _"stillərdən daha tez işləyir."_
- In sentence _"JavaScript-də tərtib edilməsi metodu"_ feels like we are losing context. How about using phrase like "JavaScript ilə" or "JavaScript istifadə edərək"?
- Another incompatibility between documents: _"3-cü tərəfli kitabxanalar"_ instead of **"üçüncü tərəf"**
- Just a suggestion, how about using "göstərə bilərsiniz" or "istifadə edə bilərsiniz" instead of _"istinas edə bilərsiniz"_. Just seems like unnecessary complicated word.

> * [x]  [Virtual DOM and Internals](https://az.reactjs.org/docs/faq-internals.html)
- Again, no upper cases in original doc. 
- **"proqramçılar"** instead of _"adamlar"_
- "**Xeyr!**" instead of _"Yox!"_

> One more thing, is it right to translate "string" as "mətn"? "mətn" is more like "text" than "string". Isn't it misleading?

**Comment by GasimGasimzada** [comment]
@mehdiyev Thank you for your contributions! I will make changes that you mentioned this time but in the future, please create a PR and push your changes.

**Comment by mehdiyev** [comment]
One more thing, is that right translation "string" as "mətn"? "mətn" is more like "text" than "string". Isn't it misleading?

**Comment by GasimGasimzada** [comment]
This is something that I decide based on the fact that there is really no translation for string in Azerbaijani. Some people say "simli" but it creates more confusion because. String actually stands for "string of characters." Even though I know that it actually means "text," I chose "mətn"  because it is the closest that I could think of a data / scalar type that represents a string of characters.

I am very open to suggestions on this matter.

**Comment by mehdiyev** [comment]
What about not translating it? I mean, we can use original as we did with words such as "rekursiv", "render", "throttle" and so on.

**Comment by mehdiyev** [comment]
Also, can be some combinations like "simli mətn" or "simvol simi".

**Comment by GasimGasimzada** [comment]
@mehdiyev 

> Or we can consider translating it with change to avoid lost in translation. For example, some combinations like "simli mətn", "simvol simi", "mətn məlumat növü" or "xarakterlər seriyası".

Let's keep them until we are 100% done with the docs, which is very close. Then, we can come to some kind of agreement on what to do next.

**Comment by GasimGasimzada** [comment]
@mehdiyev what do you think of translating the term development to "təkmilləşmə"? My only concern is that it can create confusion. Otherwise, I think it is a good translation of the word "Development"

**Comment by mehdiyev** [comment]
What about "təkmilləşdirmə"? Btw, we also should consider connected term"developer". Translate it as _"proqramçı"_ or _"təkmilləşdirici"_?

**Comment by GasimGasimzada** [comment]
For the term developer, I have done it in a lot of places. I think the only place where I haven't done it is when the term is "developer tools" or something similar.

> What about "təkmilləşdirmə"? 

doesn't matter. one or another.

**Comment by mehdiyev** [comment]
Okay then. I think it is good translation and I feel like we shouldn't be worried about confusion. Azerbaijani is not rich with technical terms but it should and it is getting updates by time. And we are kind of part of it. ReactJS is a very popular lib and its documentation can be used as reference for translations of tech terms. So, we can kind of start with new translation of tech terms, aware or unaware. And with new terms of course will be some confusions at the beginning till community accepts it.

**Comment by GasimGasimzada** [comment]
@mehdiyev I have been thinking about the word "string" and what do you think of "simvollar ardıcıllığı" or "simvollar simi"?

**Comment by mehdiyev** [comment]
@GasimGasimzada I think "simvollar simi" is better. It contains word "sim" which is literal translation of "string" and it is more specific.
